### ISSUE TITLE
Add fancy shmancy slack post summaries

### ISSUE THREAD

**Issue by adamblanchard** [skybet/skybet.github.io#104]
Slack uses meta data from links to make them look nice in slack. 

In the first message in the screenshot you can see an example of mondo who add reading time and likes to the summary. We already calculate reading time so we could easily add that.

<img width="715" alt="screen shot 2016-07-08 at 15 09 58" src="https://cloud.githubusercontent.com/assets/669429/16690299/19b8e1aa-451f-11e6-8f07-8bc15fceb498.png">

Also note in the second message (which shows what our links currently look like), we have "&amp;" in the title which could look better, and we could also add our favicon too (as the first message shows).

**Comment by ThomasLomas** [comment]
👍

**Comment by MartinBlackburn** [comment]
Made a start on this, but ran out of time. so i'll carry on with it later next week

**Comment by adamblanchard** [comment]
@MartinBlackburn Did you manage to get this working?

**Comment by MartinBlackburn** [comment]
no, i never got time to finish it :(
its not that hard to do, just some meta tags
