### ISSUE TITLE
Layout metadata change

### ISSUE THREAD

**Issue by ant1441** [skybet/skybet.github.io#111]
In Jekyll 3 the way you use the metadata defined in _layout's changed. They are now accessed by `{{ layout.var }}` instead of `{{ page.var }}`.

See: http://jekyllrb.com/docs/upgrading/2-to-3/#layout-metadata

This can be seen by looking at a post's `og:type` meta tag, which now says "website" (due to the `isArticle` variable)

Some of these (such as `isArticle`) are a simple fix, but I'm not sure what to do with some of the others.

**Comment by WheresAlice** [comment]
I believe #112 resolves the main problem here and that we don't actually have to do anything else here?
