### ISSUE TITLE
Replace icons with new designs

### ISSUE THREAD

**Issue by adamhepton** [skybet/skybet.github.io#193]
Where product icons (Bet/Vegas/Casino/Bingo/Super 6 etc) have changed, replace them with the new designs as per live.

**Comment by WheresAlice** [comment]
there's also at least one product not listed in the footer.  Can we find where the header on m.skybet.com comes from and just steal that?

**Comment by adamhepton** [comment]
Seems sensible. I can definitely source that.

**Comment by adamhepton** [comment]
Not entirely sure when this happened, but the images are up-to-date
