### ISSUE TITLE
Font Awesome + Adblock

### ISSUE THREAD

**Issue by cmbuckley** [skybet/skybet.github.io#22]
See FortAwesome/Font-Awesome#1799; missing some brand icons when using [Fanboy's Social Blocking List](https://easylist-downloads.adblockplus.org/fanboy-social.txt).

Debatable whether to do anything about this one, though it does look a little ugly:

![Missing brand icons](https://cloud.githubusercontent.com/assets/80938/10680715/0b6fc5cc-791a-11e5-8d0c-5fda0f4e5a7b.png)

**Comment by adamhepton** [comment]
I'd say that if someone has asked to block all social media-related content, we should not try and circumvent their desire. I would also guess that we won't be the only site on the web that these users fall foul of blank content. Not really something we can detect and conditionally include but I guess we could handle failure more gracefully.

**Comment by cmbuckley** [comment]
Adblock unlinks anchors with FA's social media classes. If we really wanted to work around, we could pull in FA's SCSS and define a custom `$fa-css-prefix`. Will have a think about this
