### ISSUE TITLE
Update SBG branding

### ISSUE THREAD

**Issue by adamhepton** [skybet/skybet.github.io#260]
Main header logo and favicon, potentially other places, use a "capitals" style of the SBG logo: needs a good audit and subsequent implementation to have visual consistency throughout, particularly any places where we've matched up with all-caps in SkyFont - so not as simple as "switch an image".

/cc @FirsRdJnr for either information or implementation

**Comment by cmbuckley** [comment]
Just putting together a lower-case version of the SVG logo, but you're right we should do the rest of the icons too.

**Comment by WheresAlice** [comment]
I believe it's just the images in https://github.com/skybet/skybet.github.io/tree/master/images/logos that need updating for this?
