### ISSUE TITLE
Remove people who've left from the 'Meet the SBG team' section

### ISSUE THREAD

**Issue by TomNomNom** [skybet/skybet.github.io#54]
Inevitably we're going to have people who write blog posts and later leave the company. There's at least one person in the 'Meet the SBG team' section at the moment who doesn't work for us any more.

We need a way to handle articles written by people who have left... Do we keep their profile but take them out of the 'Meet the SBG team' section? Do we change their profile to say they've left?

**Comment by glenjamin** [comment]
I'd suggest having a former members section.

**Comment by adamhepton** [comment]
Have gone for the easy option - add a flag for those that have left and only display on the authors section if that flag isn't present.

**Comment by cmbuckley** [comment]
:+1:

**Comment by cmbuckley** [comment]
@adamhepton Can you send over a proper PR for this?

**Comment by adamhepton** [comment]
Try this one @cmbuckley - https://github.com/skybet/skybet.github.io/pull/71
