### ISSUE TITLE
Jekyll 3.0

### ISSUE THREAD

**Issue by ThomasLomas** [skybet/skybet.github.io#58]
https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

This mentions that "Starting May 1st, 2016, GitHub Pages will only support kramdown, Jekyll's default Markdown engine."

In _config.yml we are using redcarpet.

**Comment by medains** [comment]
Had a go switching: https://github.com/skybet/skybet.github.io/pull/61
We should do it sooner rather than later

**Comment by adamhepton** [comment]
See Issue #46 for the original attempt to use Kramdown, and the reason why it doesn't take on its own is #51 : there are some dependencies in our gemfile that differ to GH Pages'

**Comment by adamhepton** [comment]
Have opened a pull request with Colin's original upgrade work to do the other parts needed (see medains/skybet.github.io#1)

**Comment by medains** [comment]
Should be dealt with by https://github.com/skybet/skybet.github.io/pull/63 - hopefully nothing more to do here.
