### ISSUE TITLE
Inbound link from Bet footer

### ISSUE THREAD

**Issue by robtuley** [skybet/skybet.github.io#8]
Add a link from https://www.skybet.com footer.

**Comment by cmbuckley** [comment]
Should agree on the link text etc for this and #9, e.g. "Engineering blog":

![Engineering blog link](https://cloud.githubusercontent.com/assets/80938/10018674/8eff70b0-6130-11e5-9637-0dc6e2e22602.png)

**Comment by robtuley** [comment]
I'd capitalise the 'b' : "Engineering Blog".

**Comment by cmbuckley** [comment]
OK, in which case "About Us" and "Career Opportunities" should both be title-cased.

**Comment by adamhepton** [comment]
I have discussed with Paul Mc who was not in favour of my "do it now and ask for forgiveness later" approach to this, and suggests I should involve Product and Content: which I will do.

**Comment by cmbuckley** [comment]
I stuck with your approach… it's on the desktop poker/bingo/account pages now

**Comment by adamhepton** [comment]
Product were not in favour, they suggested it should be a link from within the Careers section.  Ladies and Gentleman, we have reached a political impasse.  Deploying @robtuley ;)

**Comment by anatomic** [comment]
I'm prepared to sacrifice a little political capital to get this moving by acting now and seeking forgiveness

**Comment by cmbuckley** [comment]
Bet's lagging behind now :smile: Any plan to add this in?

**Comment by ls12styler** [comment]
@anatomic @adamhepton ??

**Comment by adamhepton** [comment]
Given that we have struggled to get people to agree that it should be there, and we are ditching the desktop site (which has links to other places) in favour of the mobile site (which does not), we should close this as unresolved.
