### ISSUE TITLE
Category Pages 

### ISSUE THREAD

**Issue by adamblanchard** [skybet/skybet.github.io#81]
Currently no way to view all posts in a category. The tags on posts are not clickable. They should link to a category page where you can view all posts in that category.

This was attempted in https://github.com/skybet/skybet.github.io/pull/50 and works locally but custom plugins are not supported by github pages so was reverted.

Some possible solutions:

1. Change deployment process so we can build pages then deploy the generated pages to github. Same solution as above, but some work around deploying/building required.
2. Stop using github pages so we can have a more customisable blog using custom plugins.

**Comment by ThomasLomas** [comment]
With the merge of #96 this could be closed. Can always revisit the implementation if need be.
