### ISSUE TITLE
Inbound link from Vegas/etc footer

### ISSUE THREAD

**Issue by robtuley** [skybet/skybet.github.io#9]
Add inbound links to the site from the gaming sites footers.

**Comment by cmbuckley** [comment]
In place on desktop poker/bingo/account pages, to be added separately to mobile poker/bingo pages and vegas desktop.

**Comment by ls12styler** [comment]
Vegas desktop link included. IMO no point in doing mobile vegas as that's going to be replaced pretty soon.

**Comment by cmbuckley** [comment]
This is included everywhere on gaming products now
